version: "3.9"
services:
  kvm-backend:
    build: Backend
    environment:
      - DATABASE_URL=/var/openfairdb/openfairdb.sqlite
      - MAIL_GATEWAY_SENDER_ADDRESS=no-reply@alexreiner.de
    ports:
      - "6767:8000"
    volumes:
      - ./data/openfairdb:/var/openfairdb/
    profiles:
      - donotstart

  kvm-frontend-dev:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile-dev
    labels:
      - traefik.http.routers.${DEV_ROUTE}.rule=Host(`${DEV_HOST}`)
      - traefik.http.routers.${DEV_ROUTE}.tls=true
      - traefik.http.routers.${DEV_ROUTE}.tls.certresolver=lets-encrypt
      - traefik.http.services.${DEV_ROUTE}.loadbalancer.server.port=3001
    networks:
      - web
    profiles:
      - donotstartdev

  kvm-frontend-prod:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-prod
      args:
        NEXT_PUBLIC_SELF_DOMAIN: https://${PROD_HOST}
    environment:
      - NEXT_PUBLIC_SELF_DOMAIN=https://${PROD_HOST}
    labels:
      - traefik.http.routers.${PROD_ROUTE}.rule=Host(`${PROD_HOST}`) && !PathPrefix(`/public`)
      - traefik.http.routers.${PROD_ROUTE}.tls=true
      - traefik.http.routers.${PROD_ROUTE}.tls.certresolver=lets-encrypt
      - traefik.http.services.${PROD_ROUTE}.loadbalancer.server.port=3000
    volumes:
      - frontend_db:/frontend/db
    networks:
      - web
    depends_on:
      - kvm-frontend-prod-tagsync

  kvm-frontend-prod-tagsync:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-tagsync
    volumes:
      - frontend_db:/frontend/db
    labels:
      - traefik.enable=false

  kvm-syncthing:
    image: syncthing/syncthing
    restart: unless-stopped
    labels:
      - traefik.http.routers.kvm-syncthing.rule=Host(`${SYNCTHING_HOST}`)
      - traefik.http.services.kvm-syncthing.loadbalancer.server.port=8384
      - traefik.http.routers.kvm-syncthing.tls=true
      - traefik.http.routers.kvm-syncthing.tls.certresolver=lets-encrypt
    volumes:
      - ./data/syncthing:/var/syncthing
    networks:
      - web
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp

  kvm-syncthing-public:
    image: 'httpd:latest'
    labels:
      - traefik.http.routers.kvm-syncthing-public.rule=Host(`${PROD_HOST}`) && PathPrefix(`/public`)
      - traefik.http.routers.kvm-syncthing-public.tls=true
      - traefik.http.routers.kvm-syncthing-public.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web
    volumes:
      - './data/syncthing:/usr/local/apache2/htdocs/public/'

networks:
  web:
    external: true
volumes:
  frontend_db: