version: "3.9"
services:
  kvm-frontend-prod:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-prod
      args:
        NEXT_PUBLIC_SELF_DOMAIN: https://${PROD_HOST}
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NEXT_PUBLIC_SELF_DOMAIN=https://${PROD_HOST}
    volumes:
      - frontend_db:/frontend/db
      - './data/syncthing:/frontend/public/'
    depends_on:
      - kvm-frontend-prod-tagsync

  kvm-frontend-prod-tagsync:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-tagsync
    volumes:
      - frontend_db:/frontend/db
    labels:
      - traefik.enable=false

  kvm-syncthing:
    image: syncthing/syncthing
    restart: unless-stopped
    volumes:
      - ./data/syncthing:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - "127.0.0.1:3001:8384"

  kvm-syncthing-public:
    image: 'httpd:latest'
    ports:
      - "127.0.0.1:3002:80"
    volumes:
      - './data/syncthing:/usr/local/apache2/htdocs/public/'

volumes:
  frontend_db: