version: "3.9"
services:
  kvm-backend:
    build: Backend
    environment:
      - DATABASE_URL=/var/openfairdb/openfairdb.sqlite
      - MAIL_GATEWAY_SENDER_ADDRESS=no-reply@alexreiner.de
    ports:
      - "6767:8000"
    volumes:
      - ./data/openfairdb:/var/openfairdb/
    profiles:
      - donotstart
  kvm-frontend:
    build: Frontend
    labels:
      - traefik.http.routers.${ROUTE}.rule=Host(`${HOST}`)
      - traefik.http.routers.${ROUTE}.tls=true
      - traefik.http.routers.${ROUTE}.tls.certresolver=lets-encrypt
      - traefik.http.services.${ROUTE}.loadbalancer.server.port=3001
    networks:
      - web
    # For the sake of completenenss #
    #ports:
    #  - "3001:3001"
    #  - "3000:3000"

networks:
  web:
    external: true
  