version: "3.9"
services:
  kvm-backend:
    build: Backend
    environment:
      - DATABASE_URL=/var/openfairdb/openfairdb.sqlite
      - MAIL_GATEWAY_SENDER_ADDRESS=no-reply@alexreiner.de
    ports:
      - "6767:8000"
    volumes:
      - ./data/openfairdb:/var/openfairdb/
    profiles:
      - donotstart

  kvm-frontend-dev:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile-dev
    labels:
      - traefik.http.routers.${DEV_ROUTE}.rule=Host(`${DEV_HOST}`)
      - traefik.http.routers.${DEV_ROUTE}.tls=true
      - traefik.http.routers.${DEV_ROUTE}.tls.certresolver=lets-encrypt
      - traefik.http.services.${DEV_ROUTE}.loadbalancer.server.port=3001
    networks:
      - web
    profiles:
      - donotstart
    # For the sake of completeness #
    #ports:
    #  - "3001:3001"

  kvm-frontend-prod:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-prod
    labels:
      - traefik.http.routers.${PROD_ROUTE}.rule=Host(`${PROD_HOST}`)
      - traefik.http.routers.${PROD_ROUTE}.tls=true
      - traefik.http.routers.${PROD_ROUTE}.tls.certresolver=lets-encrypt
      - traefik.http.services.${PROD_ROUTE}.loadbalancer.server.port=3000
    volumes:
      - frontend_db:/frontend/db
    networks:
      - web
    depends_on:
      - kvm-frotend-prod-tagsync
    # For the sake of completeness #
    #ports:
    #  - "3000:3000"
  kvm-frontend-prod-tagsync:
    build:
      context: ./Frontend
      dockerfile: Dockerfile-tagsync
    volumes:
      - frontend_db:/frontend/db
    labels:
      - traefik.enable=false

networks:
  web:
    external: true
volumes:
  frontend_db: